In [1]:
import numpy as np

# 1. np.array()
arr1 = np.array([1, 2, 3, 4])

print("1. np.array():\n", arr1)


1. np.array():
 [1 2 3 4]


In [2]:
# 2. np.zeros()
arr2 = np.zeros((2, 3))
print("2. np.zeros():\n", arr2)

2. np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 3. np.ones()
arr3 = np.ones((3, 3))
print("3. np.ones():\n", arr3)

3. np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# 4. np.empty()
arr4 = np.empty((2, 3))
print("4. np.empty():\n", arr4)

4. np.empty():
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 5. np.full()
arr5 = np.full((5,5), 8)
print("5. np.full():\n", arr5)


5. np.full():
 [[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]


In [ ]:
# 6. np.arange()
arr6 = np.arange(1, 10, 2)
print("6. np.arange():\n", arr6)



In [ ]:
# 7. np.linspace()
arr7 = np.linspace(0, 10, 5)
print("7. np.linspace():\n", arr7)

In [ ]:
# 8. np.eye()
arr8 = np.eye(3)
print("8. np.eye():\n", arr8)


In [ ]:

# 9. np.random.rand()
arr9 = np.random.rand(2, 3)
print("9. np.random.rand():\n", arr9)




In [ ]:
# 10. np.random.randn()
arr10 = np.random.randn(2, 3)
print("10. np.random.randn():\n", arr10)



In [ ]:
# 11. np.random.randint()
arr11 = np.random.randint(1, 5, size=(5, 5))
print("11. np.random.randint():\n", arr11)


In [ ]:
# 12. np.fromfunction()
arr12 = np.fromfunction(lambda i, j: i + j, (3, 3))
print("12. np.fromfunction():\n", arr12)



In [ ]:
# 13. np.fromiter()
arr13 = np.fromiter(range(5), dtype=int)
print("13. np.fromiter():\n", arr13)



In [ ]:
# 14. np.fromstring()
arr14 = np.fromstring('1 2 3 4 5', sep=' ', dtype=int)
print("14. np.fromstring():\n", arr14)


In [ ]:
# 15. np.tile()
arr15 = np.tile([1, 2, 3], (2, 2))
print("15. np.tile():\n", arr15)



In [ ]:
# 16. np.copy()
original = np.array([1, 2, 3])
arr16 = np.copy(original)
print("16. np.copy():\n", arr16)


In [ ]:
# 17. np.meshgrid()
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print("17. np.meshgrid():\n", X, "\n", Y)



In [ ]:
# 18. np.diag()
arr18 = np.diag([1, 2, 3])
print("18. np.diag():\n", arr18)




In [ ]:
# 19. np.indices()
arr19 = np.indices((2, 3))
print("19. np.indices():\n", arr19)




In [ ]:
# 20. np.concatenate()
a = np.array([1, 2])
b = np.array([3, 4])
arr20 = np.concatenate((a, b))
print("20. np.concatenate():\n", arr20)